---
namespace: production
namePrefix: production-
resources:
- ../../base
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: nginx-deployment
    path: deployment-patch.yaml
